# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{get_args}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["maiha", "Yehuda Katz"]
  s.date = %q{2009-12-11}
  s.description = %q{Extracted from Merb, get_args allows you to query a method for its argument names and defaults.
      
      This gem exists so you can get this functionality without having to include all of Merb.}
  s.email = %q{crnixon@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "get_args.gemspec",
     "lib/argument_list.rb",
     "lib/get_args.rb",
     "lib/jruby_args.rb",
     "lib/mri_args.rb",
     "lib/vm_args.rb",
     "test/helper.rb",
     "test/test_argument_list.rb",
     "test/test_get_args.rb"
  ]
  s.homepage = %q{http://github.com/crnixon/get_args}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Allows one to introspect on the argument names and defaults for a method.}
  s.test_files = [
    "test/helper.rb",
     "test/test_argument_list.rb",
     "test/test_get_args.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<extlib>, [">= 0.9.13"])
    else
      s.add_dependency(%q<extlib>, [">= 0.9.13"])
    end
  else
    s.add_dependency(%q<extlib>, [">= 0.9.13"])
  end
end

